language: node_js
node_js:
  - "8"
deploy:
  provider: heroku
  api_key:
    secure: WMgQTlYSSCmQqAU7hdFsxmaI//66t9EUEAcZYyd1gjomoQ5+ESGaylblYMrdf37kf1aTguyph1+jde7h/XK1tQbGPSPYKA25fkfifWdMQjieZfqFVUXNjW6yp60PsMuec/5DcGhEVwsRE4ZAVoiJfVAZqckGXVMQZIzK1XLNfIisd7RLuV7qKaf+koQfab7L0HqoGumvdV7ZNIbfknxjPRSFsX0xHHEJaHTnf0KI3GM1HxrXkvjOiGmjxbbTHODh0kBEbd7zwNLHmeMEwvIXp2H0ta8d1YcmE3uZeYgOuc4TIOumx+e9WYZQ+CDIgrI2xNwXnUoqt4yKkdSkYOR+E6pVaBAVm+OYi27Me51yV53j0xsLrR2QAtnsGVig+jK4ZMTxmwSP/evTLif0e6ehp01Ru6wR/96903CjEiQKxqQT6Qdcmu7jAlwn2FP7Or8ow2z5igySnu7cqRzH9JNRGnzbnb+dmCix5MFuMWldy+JBHj/Tf6TR+IpugygujVPO/dgTDHIjMfw31TAst6pJtwN0hgBRgNlHvkXEAqwNDBY4/qlye3/x/h9QjqjwonF4OCPp+oohe7otKH6hrKk9j4H6DkrFwWfaQuf+Y5ePCRPlpSNq0ZhCn7ufR19whmw4VW4CMw0PMlnxxma+t4EpJrizsGWSh5AQBd4DqWk61dU=
  app: test-github-repo
  on:
    repo: jotaoncode/test-github-repo
